### ISSUE TITLE
onAdFailed이 안올경우가 많네요..

### ISSUE THREAD

**Issue by yjssin** [adfit/adfit-android-sdk#11]
새로운 앱에 적용해 보고있는데요.
버전은 3.0.5 사용했고 테스트 중이긴한데 loadAd후에 아무응답 없는 경우가 많은거 같습니다.
로드를 못했을경우 onAdFailed로 라도 와야 하는데 안오는 경우가 꽤 되는거 같습니다.
아직 승인전이고 테스트 화면이라서 그런걸까요??

**Comment by chanyhan** [comment]
@yjssin 혹시 apk를 첨부해 주실수있나요?

**Comment by yjssin** [comment]
공개된 공간이라 메일주소를 알려주시면 재현경로와 apk위치 알려드릴께요

**Comment by chanyhan** [comment]
yohan.c@kakaocorp.com , james.kang@kakaocorp.com 으로 부탁드립니다 @yjssin

**Comment by yjssin** [comment]
제 소스 문제 인듯합니다..바쁘신데 답변 주셔서 감사드립니다..
