### ISSUE TITLE
3.0.6 파일이 없어요~

### ISSUE THREAD

**Issue by yunchiri** [adfit/adfit-android-sdk#14]
ㅇ

**Comment by chanyhan** [comment]
안녕하세요~

현재 github wiki(https://github.com/adfit/adfit-android-sdk/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0)로 안내되고 있는 maven 저장소(http://devrepo.kakao.com:8088/nexus/content/groups/public/)의
"com.kakao.adfit:ads-base:3.0.6" artifact 경로(http://devrepo.kakao.com:8088/nexus/content/groups/public/com/kakao/adfit/ads-base/3.0.6/)에 aar 형태로 업로드되어 배포되고 있습니다.

aar이 필요하신 경우 위 경로를 통해 직접 다운 받으실 수 있으나,
maven pom을 통해 의존성이 설정되어 있는 라이브러리가 존재하니
되도록 maven을 통한 연동을 권장드립니다.


build.gradle
```
repositories { 
        maven{ url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/'}
}
dependencies {
    implementation 'com.kakao.adfit:ads-base:3.0.6'
}
```

**Comment by chanyhan** [comment]
FAQ issue 로 close 하지 않고, 당분간 open 상태로 유지합니다.
