### ISSUE TITLE
혹시 API28에서 오류있나요?

### ISSUE THREAD

**Issue by jnukhj** [adfit/adfit-android-sdk#15]
안녕하세요.
아직 정확한 오류 원인을 파악하지 못한 상태입니다만, 
아래 조합으로 프로젝트를 실행시키면 오류가 발생합니다.

- AndroidManifest.xml (compileSdkVersion 28 , targetSdkVersion 28) 
- 애드핏 3.0.7 버전 적용

targetSdkVersion 을 26으로 낮추거나, 애드핏 3.0.6을 적용하면 에러가 발생하지 않습니다.

테스트 환경은 이클립스와 안드로이드 스튜디오에서 각각 테스트 해보았습니다.

**Comment by chanyhan** [comment]
@jnukhj build.gradle 파일을 첨부해주실수 있나요?

**Comment by jnukhj** [comment]
이걸 올려드리면 되는지요?

1. build.gradle (Project:..)
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.0'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        flatDir {
            dirs 'libs'
        }

        // 애드핏
        maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


2. build.gradle (Module: app)
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.xxxx.xxxxx"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 645
        versionName "6.4.5"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

configurations {
    all {
        exclude module: 'httpclient'
    }
}

android {
    useLibrary 'org.apache.http.legacy'

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:+'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:multidex:1.0.0'
    implementation 'org.apache.httpcomponents:httpcore:4.4.1'
    implementation 'org.apache.httpcomponents:httpclient:4.5'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.30'
    implementation 'com.google.android.gms:play-services-ads:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    implementation 'com.google.android.gms:play-services-base:15.0.1'
    implementation 'com.kakao.adfit:ads-base:3.0.7'
}

**Comment by chanyhan** [comment]
@jnukhj  혹시 오류 메시지를 알려주실 수 있나요? 현재 재현이 되지 않고 있어, 의심이 되는 부분을 중심으로 확인 중입니다. ^^;

**Comment by jnukhj** [comment]
안드로이OS 파이(API28) 테스트폰을 반납해버린 관계로 현재는 다시 볼 수가 없습니다.
조만간 공기계 구해서 다시 진행 후, 올려드리겠습니다.

**Comment by chanyhan** [comment]
@jnukhj 정확한 오류 사항을 자세히 적어주시면 감사하겠습니다. 혹시 28 target 으로 빌드된 apk 를 보내주실 수 있나요?

**Comment by jnukhj** [comment]
개발자님 죄송합니다. 저희쪽 에러입니다.
API28에서 httpClient 관련 충돌로 인해 발생한 오류였습니다.
심려끼쳐드려 죄송합니다.
