### ISSUE TITLE
안녕하세요. 다크모드를 위한 개선 요청드립니다.

### ISSUE THREAD

**Issue by y2ducky** [adfit/adfit-android-sdk#18]
안녕하세요.

다크 테마를 사용하여 다크모드가 적용중일 때,
AdFit의 텍스트 광고(띠배너)는 배경이 흰색이라서 너무 눈이 부십니다.
텍스트 광고의 경우에는 배경과 글자의 색상을 설정/반전시킬 수 있는 API를 제공해주시거나,
자동으로 다크테마 색상을 적용하게 해주시면 좋겠습니다.
(예: res/values-night 에 배경과 글자의 색상값을 두고 이 값을 참조)

감사합니다.

**Comment by Unbalance09** [comment]
@y2ducky
안녕하세요. 
다크 모드 지원은 사업적으로 여러 부서와 커뮤니케이션이 필요한 부분이어서 
즉답 드리기 어려운점 양해 부탁드립니다. 
문의 주신 내용에 대해 개선이 이루어질 수 있도록 내부적으로 고민해보도록 하겠습니다.
