### ISSUE TITLE
여러 모듈이 있는 프로젝트에서 빌드 불가..

### ISSUE THREAD

**Issue by Marutian** [adfit/adfit-android-sdk#2]
안녕하세요

현재 프로젝트 안에 앱모듈 2개와 1개의 중앙관리 라이브러리로 앱을 제작하고 있습니다.
라이브러리가 각 앱 모듈에 연결되어 있어 필요한 컴포넌트들을 각자 사용하는 방식입니다.
따라서 라이브러리 내에 광고모듈과 광고를 보여주는 뷰를 삽입하면 작동하도록 설계되어 있었습니다.

기존 AdFit 버전은 잘 사용했는데, 이번 업데이트 권고가 내려와 업데이트를 시도했습니다.

라이브러리 모듈의 libs 폴더에 aar 파일을 넣고, 라이브러리 모듈단 build.gradle 파일에 compile() 구문과 flatDir()을 추가했습니다. 그랬더니 앱 모듈 2개에서 파일을 찾을 수 없다며 빌드실패가 발생하고 있습니다. 해결법이 있을까요? 각 앱 모듈에 Adfit을 추가하는 방법 제외하고 해결법이 있나요..

**Comment by chanyhan** [comment]
@Marutian 혹시 아래를 추가하셨나요?
```
dependencies {
	compile(name:'AdfitSDK-2.4.2', ext:'aar')
}
```

**Comment by Marutian** [comment]
네 라이브러리 단에 추가했습니다.

**Comment by ctoo-son** [comment]
안녕하세요, AdFit 담당자입니다. 

우선 답변이 늦어서 죄송합니다. 

https://cs.daum.net/question/1440.html 에 프로젝트의 구조를 확인 가능하도록 sample을 제공부탁드립니다. 
감사합니다.

**Comment by chanyhan** [comment]
각 앱 모듈에 Adfit을 추가하셔야 합니다. ^^;;;;;

repository 로 추가 할수있도록 작업중에 있으니, 조만간 쉽게 추가하실 수 있을 것입니다.
