### ISSUE TITLE
recyclerView의 item으로 사용시 문의

### ISSUE THREAD

**Issue by dwkim891220** [adfit/adfit-android-sdk#20]
안녕하세요.
kakao adfit sdk를 서비스에 사용하는데 있어 궁금한점이 생겨 문의 드립니다.
RecyclerView의 viewHolder에 'com.kakao.adfit.ads.ba.BannerAdView'를 사용하려 합니다.
특정리스트를 계속해서 추가시 반복적으로 bannerAdView에 loadAd() 를 사용하려 합니다.
lifeCycle.observer를 추가해줘야 하는데, RecyclerView를 가지는 activity에서 observer를 추가하고
setClientId를 호출해서 설정한 후 viewHolder에서 loadAd를 호출해도 문제가 없을까요?
activity의 lifeCycle이 파기되기 전 까지 viewHolder가 반복적으로 생성되고 재사용 될텐데 성능에는 문제 없나요?

**Comment by Unbalance09** [comment]
@dwkim891220 
안녕하세요. 우선 답변이 늦어 죄송합니다.

BannerAdView 1개를 위해 LifecycleObserver 여러개가 동시에 사용되지 않도록 처리해주시면 
LifecycleObserver에 대한 문제는 없을 것으로 보입니다.

BannerAdView를 재사용하실 경우, 해당 BannerAdView에서 이전에 노출 중이던 광고가 있으면 
해당 광고가 계속해서 노출되며 광고 갱신 설정에 따라 새로운 광고로 갱신됩니다.

BannerAdView 사용을 모두 끝마친 후에는 destroy()를 호출하여 폐기하시기 바랍니다.
destroy()를 호출한 BannerAdView는 더 이상 광고가 노출되지 않아 재사용하실 수 없으니 주의부탁드립니다. 

한 페이지 내에서 다수의 BannerAdView를 사용할 경우, AdFit 운영 정책의 
"3.2 콘텐츠 가이드라인"의 "지나치게 광고가 많은 콘텐츠" 항목에 해당되지 않도록 참고하시기 바랍니다.
- AdFit(애드핏) 서비스 운영정책: https://adfit.kakao.com/web/html/use_kakao.html

감사합니다.
