### ISSUE TITLE
플루터 버전은 없나요?

### ISSUE THREAD

**Issue by yunchiri** [adfit/adfit-android-sdk#21]
있다면
admob -> adfit으로 갈아타고 싶습니다

**Comment by Unbalance09** [comment]
안녕하세요 
현재 플루터 등 크로스플랫폼 환경을 지원하는 SDK를 제작할 계획은 없습니다.
작동 환경에 맞는 SDK가 호출되게끔 처리하여 사용 부탁드립니다.
감사합니다.
