### ISSUE TITLE
3.12.4 버전에서 앱 심사 리젝

### ISSUE THREAD

**Issue by hsjdeveloper** [adfit/adfit-android-sdk#24]
구글로부터 받은 거절 내용은 다음과 같습니다.

Kakao SDK 3.12.4 버전 입니다.

===================================

앱이 영구 장치 식별자를 수집하는 Kakao SDK/라이브러리를 사용하는 것으로 확인되었습니다. 영구적인 기기 식별자는 다른 개인 정보 및 민감한 사용자 데이터 또는 재설정 가능한 기기 식별자 (예: IMEI, IMSI, SIM 일련 번호 등)와 연결할 수 없습니다.

이 문제를 해결하기 위해 이 알림이 발송된 날짜(2022년 5월 17일)로부터 60일 이내에 해당 SDK를 제거해주시기 바랍니다.

또한 앱이 [개발자 정책 센터](https://play.google.com/about/developer-content-policy/)에 명시된 기타 모든 정책을 준수하는지 다시 한번 확인하시기 바랍니다. 이후에 앱에서 또 다른 정책 위반이 발생하면 추가 조치가 취해질 수 있습니다.

**Comment by Unbalance09** [comment]
@hsjdeveloper 
안녕하세요. AdFit Android SDK 담당자입니다.
해당 내용에 대해 AdFit SDK 3.12.4 버전부터는 동일한 문제가 발생하지 않음을 구글 측으로부터 확인받은 상태입니다.
혹시 메일의 내용이 수정된 AdFit SDK를 사용하는 신규 버전 앱이 아닌 현재 스토어에 게시되어 있는 앱 또는 
테스트 트랙에 게시되어 있는 다른 버전 앱에 대한 내용이 아닌지 확인부탁드립니다.

신규 버전 앱 심사가 중단된 경우, 신규 버전 AdFit SDK(3.12.4 버전 이상, 최신 3.12.6 버전)를 사용한 앱으로 다시 시도부탁드리며 
동일한 사유로 리젝될 경우, AdFit 광고 단위 정보와 앱 패키지명 등 앱 정보와 함께 재문의 부탁드리겠습니다.

감사합니다.

**Comment by Unbalance09** [comment]
추가 이슈 없는 것으로 보여 종료처리하도록 하겠습니다.
감사합니다.
