### ISSUE TITLE
가이드 문서에 오류

### ISSUE THREAD

**Issue by jinsnet** [adfit/adfit-android-sdk#25]
가이드 문서에 sdk 추가 부분에 

`maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }`

부분이 아직도 맞는지 확인 부탁 드립니다.

**Comment by Unbalance09** [comment]
https 로 설정하시면 됩니다.
`maven { url 'https://devrepo.kakao.com/nexus/content/groups/public/' }`
https://github.com/adfit/adfit-android-sdk/blob/master/build.gradle#L22

해당 부분 수정해두겠습니다.
제보 감사합니다.

**Comment by jinsnet** [comment]
빠른 답변과 수정 감사합니다!
