### ISSUE TITLE
Flutter 전용 SDK 는 계획이 있으신가요?

### ISSUE THREAD

**Issue by hajini** [adfit/adfit-android-sdk#28]
개인이 제작하신 flutter_adfit 은 있는데, 
아무래도 공식 SDK 는 아니다 보니, 버전 업데이트에 대한 대응이 안되어 사용이 어렵네요. 

https://pub.dev/packages/flutter_adfit

혹시 공식적으로 Flutter 를 지원하실 계획이 있으신지 궁금합니다.

**Comment by Unbalance09** [comment]
안녕하세요
현재 플루터 등 크로스플랫폼 환경을 직접 지원할 계획은 없습니다.
작동 환경에 맞는 SDK가 호출되게끔 처리하여 사용 부탁드립니다.
감사합니다.
