### ISSUE TITLE
플레이스토어 정책이슈

### ISSUE THREAD

**Issue by jenthous** [adfit/adfit-android-sdk#29]
**버그 내용**
플레이스토어에서 업데이트중 메일을 회신받았습니다.

아래는 메일 내용입니다.

앱 관련 문제
--
이 앱은 Android ID 및 광고 ID를 수집하는 카카오 AdFit SDK를 사용합니다. 영구적인 기기 식별자는 다른 개인 정보 및 민감한 사용자 데이터 또는 재설정 가능한 기기 식별자와 연결할 수 없습니다.SDK 제공업체에서 제공하는 경우 정책을 준수하는 버전의 SDK로 업그레이드하거나 다른 SDK로 이전하는 것이 좋습니다. 자세한 내용은 SDK 제공업체에 문의하시기 바랍니다.

사용자 데이터 정책 관련 정보
--
앱을 통해 획득한 개인 정보 및 민감한 사용자 데이터의 액세스, 수집, 사용, 공유는 사용자가 합리적으로 예상하는 목적에 부합하는 앱 및 서비스 기능과 정책으로 제한됩니다.영구적인 기기 식별자는 다음 용도를 제외하고는 다른 개인 정보 및 민감한 사용자 데이터 또는 재설정 가능한 기기 식별자와 연결할 수 없습니다.SIM 아이덴티티와 연결된 전화 통신(예: 이동통신사 계정에 연결된 Wi-Fi 통화)기기 소유자 모드를 사용하는 기업 기기 관리 앱이러한 용도는 사용자 데이터 정책에 명시된 대로 사용자에게 명확하게 공개되어야 합니다. 대체 고유 식별자에 관한 자세한 내용은 고유 식별자 권장사항을 참고하세요.

사용자 데이터 정책 관련 정보
앱을 통해 획득한 개인 정보 및 민감한 사용자 데이터의 액세스, 수집, 사용, 공유는 사용자가 합리적으로 예상하는 목적에 부합하는 앱 및 서비스 기능과 정책으로 제한됩니다.

영구적인 기기 식별자는 다음 용도를 제외하고는 다른 개인 정보 및 민감한 사용자 데이터 또는 재설정 가능한 기기 식별자와 연결할 수 없습니다.

- SIM 아이덴티티와 연결된 전화 통신(예: 이동통신사 계정에 연결된 Wi-Fi 통화)
- 기기 소유자 모드를 사용하는 기업 기기 관리 앱

이러한 용도는 [사용자 데이터](https://notifications.google.com/g/p/APdRdFzbkIiyPfpg8q5jSK_iK68iNDjF3S_w3WJ9CIZ_IQT4ZZPdv1wPLwu82OcRuhxMShTcH6umjQnVREAdV8Y_RCJRtmavxt13g5C5QNPJdBXEbJJeA8YYbSL2VBcPTIaXK-eQxPXBXcKm5xnEp-u-ydbqHhhJGZbakLUaZkBXcX0fYSkBKaGG_94DgYOe1KH-4IrwbJz554lnSQM4JWC0aFxXMViHk3Cy0XoSkKsHQ5MGAsSH) 정책에 명시된 대로 사용자에게 명확하게 공개되어야 합니다. 대체 고유 식별자에 관한 자세한 내용은 [고유 식별자 권장사항](https://notifications.google.com/g/p/APdRdFyCy2UZSIsk45EGOH0n5_w85wcZ2wlbOUzas-GAawVKEcXInz2g2RWV_ZgVbE1ZOt1TaRfHMleg4bt00RDro6q8LjTaK9RPoIyOwWhtaO-YuW3BW_a1c3aJRJTjDMxxe2dRHSjRuj3ed9qrwOISqXQwqnDD_PXT-EovxKhUwx6NLK1clCUF9GVb5bez0j0gb046SqOowKdME-rJji4DnSLWBeTYs1PpvPs)을 참고하세요.

**Comment by Unbalance09** [comment]
안녕하세요. AdFit Android SDK 담당자입니다.
과거 버그 트래킹 용도로 AdFit SDK 내에서 Android ID를 사용하였으나, 
Android ID를 광고 ID와 연계해서 사용하면 광고 ID 초기화 기능을 무력화할 수 있다는 문제가 인입되어서 
[AdFit SDK v3.11.11 버전](https://github.com/adfit/adfit-android-sdk/releases/tag/v3.11.11)에서 해당 부분 제거 처리되었습니다.

사용 중이신 SDK를 최신 버전으로 업데이트하시면 문제가 해결될 것으로 보이며, 
문제가 지속된다면 재문의 부탁드립니다.

감사합니다.
