### ISSUE TITLE
이클립스도 살펴주셨으면 감사하겠습니다.

### ISSUE THREAD

**Issue by Kim-HJ** [adfit/adfit-android-sdk#3]
AdFit 서비스 오픈부터 현재까지 사용하고 있는 개발자입니다.
사정상 이클립스에서 안드로이드 스튜디오로 개발환경을 옮기지 못하고 있습니다.
AdFit에 이클립스에 관련된 공식적인  가이드문서와  jar파일 등을 원하는것은 아닙니다.
다만, 보편적으로 알려진 aar파일을 이클립스에서 라이브러리화하여 사용했을때 정상적을 작동되게 해주셨으면 하는게 저의 바람입니다.
현재 버전은 이클립에서 라이브러리로 사용할 경우, 정상적으로 광고 호출 > 노출 > 클릭까지만 작동되며.
문제가 되는 부분이, 광고를 클릭했을때 해당 광고 페이지(ex:웹뷰)로 넘어가지는 않는다는 것입니다.
아마도 개발자분들이 조금만 손보시면 될 것 같긴한데... 
혹시 다음 버전에서 가능하시다면, 해당 내용을 참고해주셨으면 감사하겠습니다.

**Comment by chanyhan** [comment]
https://devtalk.kakao.com/t/adfit-sdk/40816 에서 계속 이야기하는 것이 좋을 것 같습니다. ^^;
