### ISSUE TITLE
onAdLoaded 가 호출되었으나 광고가 표시되지 않는 경우

### ISSUE THREAD

**Issue by yssong04** [adfit/adfit-android-sdk#8]
정상적이라는 onAdLoaded 가 호출되었으나 광고가 표시되지 않는 경우

1. 대체광고에 설정이 표시되거나
2. 또는 광고가 표시되지 않는 reason Code를 주셔야 

개발자 입장에서는 OnAdFailed도 아니니 확인할 길이 없습니다.

**Comment by yssong04** [comment]
광고 표시되는 것 확인하고 심사요청드렸는데
다음에서 광고 제공못하는 사유로 심사보류 처리 하시니 ( Adfit FAQ참조)
받아드리기 어렵군요.

**Comment by chanyhan** [comment]
@yssong04  한번 빈 Activity 에 광고뷰 하나만을 넣어서 정상적으로 표시되는지 확인해보셨으면 합니다.

**Comment by yssong04** [comment]
@chanyhan  말씀하신대로 하시니 출력됩니다. 문제는 오전에 광고 뜨는 것 확인하고 앱 포스팅했는데 이후 동작을 안해서. 배너를 상단에 배치하면 문제 있는 것인지요?

**Comment by yssong04** [comment]
해결하였습니다.

**Comment by yssong04** [comment]
도움 주신 덕분에 1)번은 해결되어 정상적으로 배너가 출력됩니다.


하지만 2)번 교사용 앱은 onAdFailed 302가 갱신주기마다 100% 입니다.
1)번 학생용 앱도 간헐적으로 302가 발생합니다.

02-21 02:42:17.811 31486-31486/com.metadesk.ttv.timetableviewert D/### MainA:: onAdFailed : 302 reason:광고는 정상적으로 요청했으나 광고서버에서 보내줄 광고가 없음.(NO_AD)
02-21 02:43:17.951 31486-31486/com.metadesk.ttv.timetableviewert D/### MainA:: onAdFailed : 302 reason:광고는 정상적으로 요청했으나 광고서버에서 보내줄 광고가 없음.(NO_AD)
02-21 02:44:17.921 31486-31486/com.metadesk.ttv.timetableviewert D/### MainA:: onAdFailed : 302 reason:광고는 정상적으로 요청했으나 광고서버에서 보내줄 광고가 없음.(NO_AD)

시간표 출력 로직만 다를 뿐 layout , build.gradle 동일한 앱들입니다.
정상요청되었는데 NO_AD면 서버측 조치가 있어야 하는 것 아닌가 하여 도움 요청드립니다.


YS SONG
+82 10 2990 5499
 

보낸 사람: Juan Chang
보낸 날짜: 2018년 2월 20일 화요일 오후 2:34
받는 사람: adfit/adfit-android-sdk
참조: yssong04; Mention
제목: Re: [adfit/adfit-android-sdk] onAdLoaded 가 호출되었으나 광고가 표시되지 않는 경우 (#8)

@yssong04 한번 빈 Activity 에 광고뷰 하나만을 넣어서 정상적으로 표시되는지 확인해보셨으면 합니다.
